export const implantes =[
  
    {
        name:"Unitite Prime",
        altura:['8.5','10','11.5','13','15'],
        largura:['3.5','4.3','5'],
        plataforma:"CM",
        empresa: "S.i.n.",
        osso: ['I','II','III','IV'],
        pdf: "https://sin-implant.s3.us-west-2.amazonaws.com/2019/09/sin-implant-system-catalogo-unitite-v10.pdf#page=8",
        imagem: "./assets/unititeprime.png",
        valor:"$120",
      },
      {
        name:"Unitite Slim",
        altura:['10','11.5','13'],
        largura: ['2.9'],
        plataforma:"CM" ,
        empresa: "S.i.n.",
        osso: ['I','II','III','IV'],
        pdf: "https://sin-implant.s3.us-west-2.amazonaws.com/2019/09/sin-implant-system-catalogo-unitite-v10.pdf#page=14",
        imagem: "./assets/slim.png",
        valor:"$120",
      },
      {
        name:"Unitite Compact",
        altura:['5','6','7'],
        largura:['4','5','6'],
        plataforma:"CM",
        empresa: "S.i.n.",
        osso: ['I','II','III','IV'],
        pdf: "https://sin-implant.s3.us-west-2.amazonaws.com/2019/09/sin-implant-system-catalogo-unitite-v10.pdf#=17",
        imagem: "./assets/compact.png",
        valor:"$120",
      },
      {
        name:"Epikut CM",
        altura:['8.5','10','11.5','13','15'],
        largura:['3.5','3.8','4.5','5'],
        plataforma:"CM",
        empresa: "S.i.n.",
        osso: ['I','II','III','IV'],
        pdf: "https://sin-implant.s3.us-west-2.amazonaws.com/2020/10/sin-catalogo-epikut-v07-web.pdf#page=10",
        imagem: "./assets/epkutcm.png",
        valor:"$120",
      },
      {
        name:"Epikut HE",
        altura:['7','8.5','10','11.5','13','15'],
        largura:['3.5','4.5','5'],
        plataforma:"HE",
        empresa: "S.i.n.",
        osso: ['I','II','II','III'],
        pdf: "https://sin-implant.s3.us-west-2.amazonaws.com/2020/10/sin-catalogo-epikut-v07-web.pdf#page=17",
        imagem: "./assets/epkut_he.png",
        valor:"$120",
      },
    
      {
        name:"Strong SW",
        altura:['8.5','10','11.5','13','15'],
        largura:['4.5'],
        plataforma:"HE",
        empresa: "S.i.n.",
        osso: ['I','II','III','IV'],
        pdf: "https://sin-implant.s3.us-west-2.amazonaws.com/2019/09/sin-implant-system-catalogo-strong-sw.pdf#page=8",
        imagem: "./assets/strong_he.png",
        valor:"$120",
      },
    
      {
        name:"Strong SW",
        altura:['7','8.5','10','11.5','13','15'],
        largura:['3.75','5'],
        plataforma:"HE",
        empresa: "S.i.n.",
        osso: ['I','II','III','IV'],
        pdf: "https://sin-implant.s3.us-west-2.amazonaws.com/2019/09/sin-implant-system-catalogo-strong-sw.pdf#page=8",
        imagem: "./assets/strong_he.png",
        valor:"$120",
      },
    
      {
        name:"Strong SW",
        altura:['8.5','10','11.5','13','15'],
        largura:['3.8','4.5','5'],
        plataforma:"HI",
        empresa: "S.i.n.",
        osso: ['I','II','III','IV'],
        pdf: "https://sin-implant.s3.us-west-2.amazonaws.com/2019/09/sin-implant-system-catalogo-strong-sw.pdf#page=15",
        imagem: "./assets/strong_he.png",
        valor:"$120",
      },
      {
        name:"Strong SW 16º",
        altura: ['8.5','10','11.5','13','15'],
        largura:['3.5','3.8','4.5','5'],
        plataforma:"CM",
        empresa: "S.i.n.",
        osso: ['I','II','III','IV'],
        pdf: "https://sin-implant.s3.us-west-2.amazonaws.com/2019/09/sin-implant-system-catalogo-strong-sw.pdf#page=21",
        imagem: "./assets/cm16.png",
        valor:"$120",
      },
      {
        name:"Strong SWC 11,5º",
        altura: ['8.5','10','11.5','13','15'],
        largura:['3.5','3.8','4.5','5'],
        plataforma:"CM",
        empresa: "S.i.n.",
        osso: ['I','II','III','IV'],
        pdf: "https://sin-implant.s3.us-west-2.amazonaws.com/2019/09/sin-implant-system-catalogo-strong-sw.pdf#page=23",
        imagem: "./assets/cm11.5.png",
        valor:"$120",
      },
      // IMPLANTES CONEXÃO
      {
        name:"Flash®",
        altura: ['8.5','10','11.5','13','15'],
        largura:['3.5','4.3','5'],
        plataforma:"CM",
        empresa: "Conexão",
        osso: ['III','IV'],
        pdf: "https://www.conexao.com.br/catalogo/Catalogo_Final2018.pdf#page=5",
        imagem: "./assets/flash.png",
        valor:"$120",
      },
      {
        name:"Torq®",
        altura: ['8.5','10','11.5','13','15'],
        largura:['3.5','3.75'],
        plataforma:"CM",
        empresa: "Conexão",
        osso: ['I','II','III','IV'],
        pdf: "https://www.conexao.com.br/catalogo/Catalogo_Final2018.pdf#page=6",
        imagem: "./assets/torq.png",
        valor:"$120",
      },
      {
        name:"Torq®",
        altura: ['8.5','10','11.5','13'],
        largura:['4','5'],
        plataforma:"CM",
        empresa: "Conexão",
        osso: ['I','II','III','IV'],
        pdf: "https://www.conexao.com.br/catalogo/Catalogo_Final2018.pdf#page=6",
        imagem: "./assets/torq.png",
        valor:"$120",
      },
      {
        name:"Easy®",
        altura: ['8.5','10','11.5','13','15'],
        largura:['3.75'],
        plataforma:"HE",
        empresa: "Conexão",
        osso: ['I','II','III','IV'],
        pdf: "https://www.conexao.com.br/catalogo/Catalogo_Final2018.pdf#page=7",
        imagem: "./assets/easy.png",
        valor:"$120",
      },
      {
        name:"Easy®",
        altura: ['7','8.5','10','11.5','13'],
        largura:['4','5'],
        plataforma:"HE",
        empresa: "Conexão",
        osso: ['I','II','III','IV'],
        pdf: "https://www.conexao.com.br/catalogo/Catalogo_Final2018.pdf#page=7",
        imagem: "./assets/easy.png",
        valor:"$120",
      },
      {
        name:"Grip®",
        altura: ['8.5','10','11.5','13','15'],
        largura:['3.75'],
        plataforma:"HE",
        empresa: "Conexão",
        osso: ['III','IV'],
        pdf: "https://www.conexao.com.br/catalogo/Catalogo_Final2018.pdf#page=8",
        imagem: "./assets/grip.png",
        valor:"$120",
      },
      {
        name:"Grip®",
        altura: ['7','8.5','10','11.5','13'],
        largura:['4','5'],
        plataforma:"HE",
        empresa: "Conexão",
        osso: ['III','IV'],
        pdf: "https://www.conexao.com.br/catalogo/Catalogo_Final2018.pdf#page=8",
        imagem: "./assets/grip.png",
        valor:"$120",
      },
    
      {
        name:"Double®",
        altura: ['8.5','10','11.5','13','15','18'],
        largura:['3.75'],
        plataforma:"HE",
        empresa: "Conexão",
        osso: ['I','II','III','IV'],
        pdf: "https://www.conexao.com.br/catalogo/Catalogo_Final2018.pdf#page=9",
        imagem: "./assets/double.png",
        valor:"$120",
      },
      {
        name:"Double®",
        altura: ['8.5','10','11.5','13','15'],
        largura:['4'],
        plataforma:"HE",
        empresa: "Conexão",
        osso: ['I','II','III','IV'],
        pdf: "https://www.conexao.com.br/catalogo/Catalogo_Final2018.pdf#page=9",
        imagem: "./assets/double.png",
        valor:"$120",
      },
      {
        name:"Short®",
        altura: ['5.5'],
        largura:['4.3','5'],
        plataforma:"HE",
        empresa: "Conexão",
        osso: ['I','II'],
        pdf: "https://www.conexao.com.br/catalogo/Catalogo_Final2018.pdf#page=10",
        imagem: "./assets/short.png",
        valor:"$120",
      },
      {
        name:"AR®",
        altura: ['10','11.5','13','15'],
        largura:['3.75','4','5'],
        plataforma:"HI",
        empresa: "Conexão",
        osso: ['I','II','III','IV'],
        pdf: "https://www.conexao.com.br/catalogo/Catalogo_Final2018.pdf#page=11",
        imagem: "./assets/ar.png",
        valor:"$120",
      },
      {
        name:"Cônico®",
        altura: ['10','11.5','13','15'],
        largura:['3.5','4.3','5'],
        plataforma:"HI",
        empresa: "Conexão",
        osso: ['III','IV'],
        pdf: "https://www.conexao.com.br/catalogo/Catalogo_Final2018.pdf#page=12",
        imagem: "./assets/conico.png",
        valor:"$120",
      }
    ]